# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

exporters:
  coralogix:
    domain: "${CORALOGIX_DOMAIN}"
    private_key: "${CORALOGIX_PRIVATE_KEY}"
    application_name: "${CORALOGIX_APP_NAME}"
    subsystem_name: "${CORALOGIX_SUBSYS_NAME}"
    timeout: 30s
    traces:
      endpoint: "ingress.${CORALOGIX_DOMAIN}:443"
    metrics:
      endpoint: "ingress.${CORALOGIX_DOMAIN}:443"
    logs:
      endpoint: "ingress.${CORALOGIX_DOMAIN}:443"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform/sanitize_spans]
      exporters: [otlp_grpc/jaeger, debug, spanmetrics, coralogix]
    metrics:
      receivers: [docker_stats, httpcheck/frontend-proxy, hostmetrics, nginx, otlp, postgresql, redis, spanmetrics]
      processors: [resourcedetection, memory_limiter]
      exporters: [otlp_http/prometheus, debug, coralogix]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter]
      exporters: [opensearch, debug, coralogix]
